name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Docker in rootless mode (To solve "Permission denied" error when removing test_app directory)
        uses: ScribeMD/rootless-docker@0.2.2
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Run tests
        # Image is created in early test stages (a100_generate_container_image_test.py)
        run: |
          pytest --run-destructive tests/
