name: Run tests

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Docker in rootless mode (To solve "Permission denied" error when removing test_app directory)
        uses: ScribeMD/rootless-docker@0.2.2
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Create docker image
        run: ./bootstrap.sh
        shell: bash
      - name: Run tests
        run: pytest tests
  
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Create docker image
        run: ./bootstrap.bat
      - name: Run tests
        run: |
          pytest tests